name = "monospace-dark"
license = "CC BY-NC 4.0"
licenselink = "https://creativecommons.org/licenses/by-nc/4.0/"
description = "A minimal hugo theme with monospaced font and dark color scheme."
homepage = ""
tags = ["minimal", "monospace", "dark", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "László Szurok"
  homepage = "https://laszloszurok.com"
